# Generated by Django 4.2.7 on 2026-03-24 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('civil_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=20)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('date_registered', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount_pledged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid')], default='unpaid', max_length=10)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='registry.member')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='PledgePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='registry.pledge')),
            ],
            options={
                'ordering': ['-date_paid'],
            },
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouse_name', models.CharField(max_length=200)),
                ('date_married', models.DateField()),
                ('priest', models.CharField(max_length=150)),
                ('principal_sponsor', models.CharField(blank=True, max_length=150)),
                ('secondary_sponsor', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages', to='registry.member')),
            ],
        ),
        migrations.CreateModel(
            name='LastRites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_administered', models.DateField()),
                ('priest', models.CharField(max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_rites', to='registry.member')),
            ],
        ),
        migrations.CreateModel(
            name='FirstHolyCommunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField()),
                ('priest', models.CharField(max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communion', to='registry.member')),
            ],
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_confirmed', models.DateField()),
                ('bishop', models.CharField(max_length=150)),
                ('confirmation_name', models.CharField(max_length=100)),
                ('sponsor', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='registry.member')),
            ],
        ),
        migrations.CreateModel(
            name='Baptism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_baptized', models.DateField()),
                ('priest', models.CharField(max_length=150)),
                ('godfathers', models.TextField(blank=True, default='', help_text='Comma-separated list of godfathers')),
                ('godmothers', models.TextField(blank=True, default='', help_text='Comma-separated list of godmothers')),
                ('birth_certificate_no', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baptism', to='registry.member')),
            ],
        ),
    ]
